import React,{useEffect,useRef,useState}from'react';
import{Pressable,Switch,Text,View}from'react-native';
import{Page,styles}from'../components/Page';
import{MODEL,predict,type ImuPoint,type Prediction}from'../ai/inference';
import{deviceServices}from'../services/device';
import{emergencyEngine}from'../services';
import{localStorage}from'../storage';

export function AiDetectionScreen(){
 const settings=localStorage.read('settings');const[enabled,setEnabled]=useState(settings.aiDetectionEnabled);const[sensorState,setSensorState]=useState('stopped');const[prediction,setPrediction]=useState<Prediction>();const[countdown,setCountdown]=useState<number>();const[latest,setLatest]=useState('No AI events yet.');const buffer=useRef<ImuPoint[]>([]);const gyro=useRef({x:0,y:0,z:0});const since=useRef(0);const lastAlert=useRef(0);const windowId=useRef('');
 useEffect(()=>{const next={...localStorage.read('settings'),aiDetectionEnabled:enabled,protectionEnabled:enabled};localStorage.write('settings',next);if(!enabled){setSensorState('stopped');return;}setSensorState('listening · ~50 Hz');try{return deviceServices.subscribeSensors(event=>{if(event.sensor==='gyroscope'){gyro.current=event;return;}buffer.current.push({acc_x:event.x,acc_y:event.y,acc_z:event.z,gyro_x:gyro.current.x,gyro_y:gyro.current.y,gyro_z:gyro.current.z});if(buffer.current.length>100)buffer.current.shift();since.current++;if(buffer.current.length===100&&since.current>=50){since.current=0;const result=predict(buffer.current);setPrediction(result);windowId.current=`window-${Date.now()}`;setLatest(`${result.predictedClass} · ${(Math.max(...Object.values(result.probabilities))*100).toFixed(1)}%`);if(result.predictedClass==='possible_fall'&&result.fallConfidence>=MODEL.possible_fall_threshold&&Date.now()-lastAlert.current>30000){lastAlert.current=Date.now();setCountdown(localStorage.read('settings').countdownSeconds);}}});}catch(error){setSensorState(error instanceof Error?error.message:String(error));setEnabled(false);}},[enabled]);
 useEffect(()=>{if(countdown===undefined)return;if(countdown<=0){setCountdown(undefined);setLatest('Fall countdown timed out; emergency workflow started.');emergencyEngine.start('ai_fall').catch(error=>setLatest(error instanceof Error?error.message:String(error)));return;}const timer=setTimeout(()=>setCountdown(value=>value===undefined?undefined:value-1),1000);return()=>clearTimeout(timer);},[countdown]);
 const safe=()=>{if(prediction)localStorage.write('falseAlarmFeedback',[{id:`feedback-${Date.now()}`,timestamp:new Date().toISOString(),prediction:prediction.predictedClass,confidence:prediction.fallConfidence,modelVersion:prediction.modelVersion,windowReference:windowId.current},...localStorage.read('falseAlarmFeedback')]);setCountdown(undefined);setLatest('False alarm cancelled and stored locally.');};
 const help=()=>{setCountdown(undefined);setLatest('Help requested; emergency workflow started.');emergencyEngine.start('ai_fall').catch(error=>setLatest(error instanceof Error?error.message:String(error)));};
 return <Page title="AI Detection"><View style={styles.card}><View style={styles.row}><Text style={styles.label}>Protection {enabled?'ON':'OFF'}</Text><Switch value={enabled} onValueChange={setEnabled}/></View><Text style={styles.muted}>Sensor: {sensorState}</Text><Text style={styles.muted}>Model: {MODEL.model_version} · offline</Text></View>{countdown!==undefined&&<View style={[styles.card,styles.alertCard]}><Text style={styles.error}>Possible Fall Detected</Text><Text style={styles.label}>Are you safe? · {countdown}s</Text><Pressable style={styles.button} onPress={safe}><Text style={styles.buttonText}>I'M SAFE</Text></Pressable><Pressable style={[styles.button,styles.dangerButton]} onPress={help}><Text style={styles.buttonText}>SEND HELP NOW</Text></Pressable></View>}<View style={styles.card}><Text style={styles.label}>Live decision</Text><Text style={styles.text}>Predicted: {prediction?.predictedClass.replaceAll('_',' ')||'waiting for 2-second window'}</Text><Text style={styles.muted}>Fall confidence: {((prediction?.fallConfidence||0)*100).toFixed(1)}%</Text><Text style={styles.muted}>Phone-drop confidence: {((prediction?.phoneDropConfidence||0)*100).toFixed(1)}%</Text><Text style={styles.muted}>Rule baseline: {prediction?.ruleResult||'waiting'}</Text><Text style={styles.muted}>ML result: {prediction?.predictedClass||'waiting'}</Text></View><View style={styles.card}><Text style={styles.label}>Latest AI event</Text><Text style={styles.text}>{latest}</Text></View><Text style={styles.muted}>A phone-drop prediction is suppressed. AI is an experimental aid, not a safety guarantee.</Text></Page>;
}
