import React, { useEffect, useRef, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { Page, styles } from '../components/Page';
import { SENSOR_LABELS, SensorSessionCollector, samplesToCsv } from '../services/sensors';
import { deviceServices } from '../services/device';
import { localStorage } from '../storage';

export function SensorCollectionScreen() {
  const [label,setLabel]=useState<string>('normal'); const [countdown,setCountdown]=useState<number>(); const [active,setActive]=useState(false); const [count,setCount]=useState(0); const [startedAt,setStartedAt]=useState<number>(); const [now,setNow]=useState(Date.now()); const [sessions,setSessions]=useState(()=>localStorage.read('sensorSessions')); const [message,setMessage]=useState(''); const collector=useRef<SensorSessionCollector | undefined>(undefined);
  useEffect(()=>{ if(!active)return; const interval=setInterval(()=>setNow(Date.now()),500); return()=>clearInterval(interval);},[active]);
  useEffect(()=>{if(countdown===undefined)return;if(countdown<=0){const next=new SensorSessionCollector(label);collector.current=next;try{next.start(setCount);setStartedAt(Date.now());setNow(Date.now());setActive(true);setMessage('');}catch(error){setMessage(error instanceof Error?error.message:String(error));}setCountdown(undefined);return;}const timer=setTimeout(()=>setCountdown(value=>value===undefined?undefined:value-1),1000);return()=>clearTimeout(timer);},[countdown,label]);
  useEffect(()=>()=>{collector.current?.stop();},[]);
  const stop=async()=>{if(!collector.current)return;const session=collector.current.stop();setActive(false);const csv=samplesToCsv(collector.current.samples);try{session.csv_path_optional=await deviceServices.saveCsv(`${session.session_id}.csv`,csv);const next=[session,...localStorage.read('sensorSessions')];localStorage.write('sensorSessions',next);setSessions(next);setMessage(`Saved ${session.sample_count} samples locally.`);}catch(error){setMessage(error instanceof Error?error.message:String(error));}collector.current=undefined;};
  return <Page title="Sensor Data Collection"><Text style={styles.text}>Collect safe, labelled accelerometer and gyroscope sessions. Never perform dangerous real falls.</Text><View style={styles.card}><Text style={styles.label}>Activity label</Text><View style={styles.row}>{SENSOR_LABELS.map(item=><Pressable key={item} disabled={active||countdown!==undefined} style={[styles.card,item===label&&styles.button]} onPress={()=>setLabel(item)}><Text style={item===label?styles.buttonText:styles.label}>{item.replaceAll('_',' ')}</Text></Pressable>)}</View>{countdown!==undefined&&<Text style={styles.error}>Starting in {countdown}…</Text>}{active?<><Text style={styles.success}>COLLECTING · {label}</Text><Text style={styles.text}>{count} samples · {startedAt?((now-startedAt)/1000).toFixed(1):'0.0'} seconds</Text><Pressable style={[styles.button,styles.dangerButton]} onPress={stop}><Text style={styles.buttonText}>Stop and save CSV</Text></Pressable></>:<Pressable style={styles.button} onPress={()=>{setCount(0);setCountdown(3);}}><Text style={styles.buttonText}>Start session</Text></Pressable>}</View>{!!message&&<Text style={styles.text}>{message}</Text>}<Text style={styles.label}>Saved sessions</Text>{!sessions.length&&<View style={styles.card}><Text style={styles.muted}>No sessions collected.</Text></View>}{sessions.map(session=><View key={session.session_id} style={styles.card}><Text style={styles.label}>{session.label.replaceAll('_',' ')}</Text><Text style={styles.muted}>{session.sample_count} samples · {new Date(session.started_at).toLocaleString()}</Text>{session.csv_path_optional&&<Pressable style={styles.button} onPress={()=>deviceServices.shareFile(session.csv_path_optional!)}><Text style={styles.buttonText}>Export / share CSV</Text></Pressable>}</View>)}</Page>;
}
